version: '3.9'

services:
  web:
    build: .
    networks:
      - proxynet
    volumes:
      - db_data:/app/db  # Monte un volume pour la base de données
    environment:
      - FLASK_ENV=production
    restart: always

networks:
  proxynet:
    name: proxynet
    external: true

volumes:
  db_data:
    driver: local